### ISSUE TITLE
Error in ask_sdk_runtime

### ISSUE THREAD

**Issue by mikekaminsky** [alexa/skill-sample-python-quiz-game#14]
I _believe_ that I followed the directions in this tutorial correctly, but I'm getting an error in the lambda logs that I cannot figure out how to debug.

```[ERROR]	2019-05-30T00:37:46.24Z	914df143-bd17-4992-947e-01b52c786918	process() got an unexpected keyword argument 'dispatch_output'
Traceback (most recent call last):
File "/var/task/ask_sdk_runtime/dispatch.py", line 122, in dispatch
handler_input=handler_input, dispatch_output=output)
TypeError: process() got an unexpected keyword argument 'dispatch_output'
```

I'm not really sure at all what could be going on here -- any ideas would be helpful! Here's the output of pip freeze:
```
ask-sdk-core==1.10.0
ask-sdk-model==1.11.0
ask-sdk-runtime==1.10.0
certifi==2019.3.9
chardet==3.0.4
idna==2.8
python-dateutil==2.8.0
requests==2.22.0
six==1.12.0
urllib3==1.25.3
```

**Comment by franklin-lobb** [comment]
Hi @mikekaminsky - looks like you are encountering the same issue as is noted here: https://github.com/alexa/alexa-skills-kit-sdk-for-python/issues/91

From that issue, it's a bug in the SDK and fix is forthcoming.  I'd suggest watching that issue for updates.

**Comment by nikhilym** [comment]
Hey @mikekaminsky , please update your `ask-sdk-runtime` to version `1.10.1`, which fixes this issue.

**Comment by mikekaminsky** [comment]
@franklin-lobb @nikhilym thanks y'all!
